### ISSUE TITLE
Override output path

### ISSUE THREAD

**Issue by rom1K** [dependency-check/Dependency-Check_Action#15]
Hey, I would need to be able to override the output path for the reports, could we modify the action to do it ? I was thinking of adding a variable with a default value:

```yaml
inputs:
  out:
    required: true
    default: 'reports'

```

and then updating[ this line ](https://github.com/dependency-check/Dependency-Check_Action/blob/931d0ddb0b93df3a66188301fc9950e911a1ddba/action.yml#L28) to use it: `'/github/workspace/${{ inputs.out }}'`

~Another improvement could be to use the `github.workspace` variable in place of `/github/workspace`~ did not know it was a mounted volume my bad, I updated the code above :S

**Comment by javixeneize** [comment]
Hi

thanks for the comment. Feel free to do a PR with the improvement suggested

m thanks

**Comment by rom1K** [comment]
Thanks for the reactivity !
