### ISSUE TITLE
The workflow fails with locally referenced modules

### ISSUE THREAD

**Issue by alex-arzaghi** [dependency-check/Dependency-Check_Action#18]
I am having trouble using the workflow to scan a repo with with locally referenced modules. When the workflow runs, I am getting a few warnings about skipping the locally referenced modules in my `package.json` and then the process fails with the following errors:
`Error:  NodeAuditAnalyzer failed on /github/workspace/package-lock.json`
`Error:  Cannot invoke "javax.json.JsonString.getString()" because the return value of "org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(String)" is null`
`Error:  Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.`

Here is how the local references look in the package.json:
```
"dependencies": {
		"@some-project/module1": "file:dist/libs/module1",
                 "@some-project/module2": "file:dist/libs/module2",
                  ....
}
```

**Comment by javixeneize** [comment]
Hi

Seems to be a problem with dependency check itself. Have you tried that in your local machine? Do you have the same issue?

**Comment by alex-arzaghi** [comment]
Hi @javixeneize 

Yes, I get the same error running `dependency-check --project "MY PROJECT" --scan "PATH TO MY PROJECT"`.

**Comment by javixeneize** [comment]
I recommend you to open an issue in the tool repo then, https://github.com/jeremylong/DependencyCheck

**Comment by alex-arzaghi** [comment]
Thanks @javixeneize. Looks like there is already an issue open there. I'll keep monitoring that.

https://github.com/jeremylong/DependencyCheck/issues/3717
