### ISSUE TITLE
Don't force `--noUpadate` flag

### ISSUE THREAD

**Issue by mvirnoche** [dependency-check/Dependency-Check_Action#27]
Given the current issue in the upstream from here: https://github.com/jeremylong/DependencyCheck/issues/6029, the action forced the `--noUpdate` flag here: https://github.com/dependency-check/Dependency-Check_Action/blob/3102a65fd5f36d0000297576acc56a475b0de98d/action.yml#L33. This flag appears to not sync when you try and pass in `--purge`.

**Comment by javixeneize** [comment]
Hi

The update is not done as part of the scan. Every night the image is recreated with the newer database

**Comment by mvirnoche** [comment]
@javixeneize When is that image created which is then used by the action? We are trying to get the upstream RetireJs fix and the action won't pull it in/force an update/purge using the CLI, best we have come up with is due to the embedded `--noUpdate` which is in the CLI args as it is burned in from your code.

**Comment by javixeneize** [comment]
It is built here - https://github.com/dependency-check/DependencyCheck_Builder/actions
